<link rel="stylesheet" href="<?php echo $link_template;?>/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/animate.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/owl.carousel.min.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/all.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/flaticon.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/themify-icons.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/magnific-popup.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/slick.css">
<link rel="stylesheet" href="<?php echo $link_template;?>/css/style.css">